CREATE DATABASE dbGSMC20240906
GO

-- Utilizar la base de datos CRMDB
USE dbGSMC20240906
GO

CREATE TABLE ProductsGSMC (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    NombreGSMC NVARCHAR(100) NOT NULL,
    DescripcionGSMC NVARCHAR(MAX),
    PrecioGSMC DECIMAL(18,2) NOT NULL
);